### PR TITLE
Use Subrepo for 3rdParty libs instead of submodule

### PR DESCRIPTION
**Pull request by carlos22**
Subrepo has the huge advantage that users of the lib don't need to do anything else then checking it out (or use it as subrepo on their own). The code of the used lib is commited as regular data and the subrepo command helps you to keep it in sync (and a lot more).

After this change the only thing a user of this lib needs to do is:
`git subrepo clone git@github.com:evonove/qnite.git 3rdparty/qnite`

More on git-subrepo: https://github.com/ingydotnet/git-subrepo

### CODE REVIEW

**Comment by silvanocerza** [comment]
Hi @carlos22! Sorry for the late response, the notification might have slipped through.

Your contribution is appreciated but I prefer we use only the native git commands. 
I think adding a new tool to manage submodules would create a new burden of knowledge to developers that want to contribute to the project. There aren't many contributors as of now and I don't want to scare newcomers either, so I prefer to keep it simple.
Submodules are a widely known tool to git users so we prefer sticking to that.

**Comment by carlos22** [comment]
Well OK. I understand but as mentioned submodules makes deployment harder. As alternative it would be possible to make releases which contain all the code.

>I think adding a new tool to manage submodules would create a new burden of knowledge to developers that want to contribute to the project. There aren't many contributors as of now and I don't want to scare newcomers either, so I prefer to keep it simple.

I think the contrary is true: If you do not change any files in the lib, the subrepo command is not even required. Submodules need to be used even if you do not change anything. And if the original repo is deleted, the code does not compile anymore. With subrepo you have the whole tree in your repo.

I will keep the subrepo version in my fork for me to have an easy install :-)

**Comment by synasius** [comment]
I'm closing this for now. @carlos22 thanks for your contribution

**Comment by kubark42** [comment]
I know this is long closed, but I'd like to echo the request to move away from submodules. They always seem to cause a lot of confusion, and when the goal is uniformity of code experience it's a lot less risky to check in the actual lib.

I ran across this problem because I couldn't figure out why nothing was compiling. Of course, I downloaded the zip bundle and so had no `git` goodness. The error messages for why the system couldn't find the file it wanted were completely opaque. If I wouldn't have had prior experience with these kind of failures, due to not checking out the entire tree, I would definitely have given up on this package.

**Pull request closed without merging**
